### ISSUE TITLE
Faking the ip 169.254.169.254 don't works on windows

### ISSUE THREAD

**Issue by richard-leon-130524** [nagyesta/assumed-identity#71]
I tried the steps of https://github.com/nagyesta/assumed-identity?tab=readme-ov-file#usage and works very well on linux.

The problem is with windows + docker desktop :

- The container starts
- It works with localhost

![image](https://github.com/nagyesta/assumed-identity/assets/170019116/a3360ca9-c0f0-42bf-98d4-f86194481488)

- But the endpoint doesn't works with the IP

![image](https://github.com/nagyesta/assumed-identity/assets/170019116/f4783d1f-b351-4f4c-b4c6-664ad16b00fb)

Any tip to solve it?

Thanks so much!!!

**Comment by nagyesta** [comment]
Hi @richard-leon-130524 ,
first of all, thank you for using Assumed Identity, and thank you for opening this issue! 

I think the situation you have described might be because, AFAIK Docker Desktop is running a WSL instance in the background to be able to run the Docker Engine. I would assume, that there must be some kind of magic in it that is forwarding the ports to localhost, but as soon as you are running on a different IP, it will be harder to reach from the Windows host. I have never used Docker Desktop on Windows, so I am afraid I am not the best person to help resolve this network/routing part of the issue.

BUT, if you are only running the Assumed Identity image for the sake of Lowkey Vault, then you might be able to find a workaround by adding additional env variables or config parameters when you are running your application. Please see more details at the various example projects listed here: https://github.com/nagyesta/lowkey-vault/tree/main?tab=readme-ov-file#example-projects

Also, please note, that the latest Lowkey Vault contains the same Assumed Identity token endpoint now on port ```:8080``` by default. You can configure this using the ```--app.token.port=80``` Lowkey Vault startup argument. This way, if you can find a way to assign the ```169.254.169.254``` IP to your machine and run Lowkey Vault [as a Jar](https://github.com/nagyesta/lowkey-vault/tree/main/lowkey-vault-app#startup-parameters), then you can leave out the whole layer of complexity coming from the Docker and WSL combination.

What do you think, would any of these options help you resolve the issue?

Thank you again!

**Comment by richard-leon-130524** [comment]
> Hi @richard-leon-130524 , first of all, thank you for using Assumed Identity, and thank you for opening this issue!
> 
> I think the situation you have described might be because, AFAIK Docker Desktop is running a WSL instance in the background to be able to run the Docker Engine. I would assume, that there must be some kind of magic in it that is forwarding the ports to localhost, but as soon as you are running on a different IP, it will be harder to reach from the Windows host. I have never used Docker Desktop on Windows, so I am afraid I am not the best person to help resolve this network/routing part of the issue.
> 
> BUT, if you are only running the Assumed Identity image for the sake of Lowkey Vault, then you might be able to find a workaround by adding additional env variables or config parameters when you are running your application. Please see more details at the various example projects listed here: https://github.com/nagyesta/lowkey-vault/tree/main?tab=readme-ov-file#example-projects
> 
> Also, please note, that the latest Lowkey Vault contains the same Assumed Identity token endpoint now on port `:8080` by default. You can configure this using the `--app.token.port=80` Lowkey Vault startup argument. This way, if you can find a way to assign the `169.254.169.254` IP to your machine and run Lowkey Vault [as a Jar](https://github.com/nagyesta/lowkey-vault/tree/main/lowkey-vault-app#startup-parameters), then you can leave out the whole layer of complexity coming from the Docker and WSL combination.
> 
> What do you think, would any of these options help you resolve the issue?
> 
> Thank you again!

## Summary

Faking the [Azure Instance Metadata Service](https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service) which default ip is 169.254.169.254 don't work on Windows. 

Thank goodness linux exist for real ci environments.

## Workaround on windows with nodejs

This variable helped me: `AZURE_POD_IDENTITY_AUTHORITY_HOST=http://localhost`

I achieved to write and read secrets with these steps:

- `docker run --rm -d  -p 8443:8443 nagyesta/lowkey-vault:2.4.13-ubi9-minimal`
- `docker run -d  -p 80:80 --rm nagyesta/assumed-identity:1.2.16`
- These en variables in the nodejs client

```
KEYVAULT_URI=https://localhost:8443
NODE_TLS_REJECT_UNAUTHORIZED=0
AZURE_POD_IDENTITY_AUTHORITY_HOST=http://localhost
```

- Write a secret:

```
const { DefaultAzureCredential } = require("@azure/identity");
const { SecretClient } = require("@azure/keyvault-secrets");
const credential = new DefaultAzureCredential();

let options = {
    serviceVersion: "7.4",
    disableChallengeResourceVerification: true, // ONLY ON CI, NEVER USE ON PROD!
};

const client = new SecretClient(process.env.KEYVAULT_URI, credential, options);

async function main(){
  const secretName = `secret-api-key`;
  const result = await client.setSecret(secretName, "changeme!!!");
  console.log("result: ", result);
}

main();
```

- Read a secret

```
const { DefaultAzureCredential } = require("@azure/identity");
const { SecretClient } = require("@azure/keyvault-secrets");
const credential = new DefaultAzureCredential();

let options = {
    serviceVersion: "7.4",
    disableChallengeResourceVerification: true, // ONLY ON CI, NEVER USE ON PROD!
};

const client = new SecretClient(process.env.KEYVAULT_URI, credential, options);

async function main(){
  var response = await client.getSecret("secret-api-key");
  console.log(response);
}

main();
```

---
Thanks you for your help and your time to develop this tool!!!

**Comment by nagyesta** [comment]
Thank you for providing this detailed description! I am glad you were able to sort out the issue!
